grails-app/domain/trainingtask/User.groovy
package trainingtask

import grails.compiler.GrailsCompileStatic
import grails.plugin.springsecurity.SpringSecurityService
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@GrailsCompileStatic
@EqualsAndHashCode(includes = 'username')
@ToString(includes = 'username', includeNames = true, includePackage = false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    SpringSecurityService springSecurityService

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [messages: Message, subscriptions: User]

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    def beforeInsert() {
        encodePassword()
    }

    def beforeUpdate() {
        if (isDirty('password')) {
            encodePassword()
        }
    }

    protected void encodePassword() {
        password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
    }

    static transients = ['springSecurityService']

    static constraints = {
        password blank: false, password: true
        username blank: false, unique: true
    }

    static mapping = {
        table 'Users'
        id column: 'UserID'
        accountExpired column: 'AccountExpired'
        accountLocked column: 'AccountLocked'
        passwordExpired column: 'PasswordExpired'
        messages sort: 'published', order: 'desc'
        subscriptions joinTable: [name: 'UsersUsers',
                                  key: 'UserSubscriptionsId',
                                  column: 'UserID']
    }

    String toString() {
        username
    }
}

grails-app/controllers/trainingtask/ReportController.groovy
package trainingtask

class ReportController {

    def reportService

    def forUser(User user) {
        if (user == null) {
            redirect(controller: 'main')
            return
        }

        response.setHeader("Content-disposition", "attachment; filename=${user.username}.pdf")
        response.contentType = "application/pdf"
        def pdf = reportService.exportMessagesToPdf(user, params)
        response.contentLengthLong = pdf.length
        response.outputStream.write pdf
    }
}

grails-app/controllers/trainingtask/UserController.groovy
package trainingtask


import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.CREATED
import static org.springframework.http.HttpStatus.NOT_FOUND

class UserController {

    static allowedMethods = [save: "POST"]

    def userService

    @Transactional(readOnly = true)
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model: [userCount: User.count()]
    }

    def show(User user) {
        respond user
    }

    def singUp() {
        respond new User(params)
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        if (user.hasErrors()) {
            respond user.errors, view: 'singUp'
            return
        }

        userService.save(user)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.registered.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def subscribe(User user) {
        if (user == null || user.hasErrors()) {
            redirect(action: 'index')
            return
        }

        userService.subscribe(user)
        redirect(action: 'show', id: user.id)
    }

    def unsubscribe(User user) {
        if (user == null || user.hasErrors()) {
            redirect(action: 'index')
            return
        }

        userService.unsubscribe(user)
        redirect(action: 'show', id: user.id)
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div id="list-user" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol>
        <g:each in="${userList}">
            <li><g:link action="show" id="${it.id}">${it.username}</g:link></li>
        </g:each>
    </ol>

    %{--            <div class="pagination">--}%
    %{--                <g:paginate total="${userCount ?: 0}" />--}%
    %{--            </div>--}%
</div>
</body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>

<div id="show-user" class="content scaffold-show" role="main">
    <h1><g:message code="default.user_info.label"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}.
        Redirect to login page <span id="timer">3</span>
        </div>
        <script>
            const timer = $("#timer");
            setTimeout(function () {
                window.location = "/login";
            }, 4000);
            setInterval(function () {
                timer.text(parseInt(timer.text()) - 1);
            }, 1000);
        </script>
    </g:if>
    <div>
        <p>
            <span class="property-label">Username</span>

            <span class="property-value" aria-labelledby="user-name-label">
                ${user.username}
            </span>
        </li>
    </div>
    <g:if test="${user?.messages?.size() == 0}">
        <p>User ${user.username} didn't publish any message yet</p>
    </g:if>
    <g:else>
        <sec:ifLoggedIn>
            <g:if test="${sec.loggedInUserInfo(field: 'username') != user.username}">
                <div>
                    <subscription:isSubscribe user="${user}">
                        <p>You followed this user</p>
                        <g:link controller="user" action="unsubscribe" id="${user.id}"
                                class="subscribe">Unsubscribe</g:link>
                    </subscription:isSubscribe>
                    <subscription:isNotSubscribe user="${user}">
                        <g:link controller="user" action="subscribe" id="${user.id}"
                                class="subscribe">Subscribe to ${user.username}</g:link>
                    </subscription:isNotSubscribe>
                </div>
            </g:if>
        </sec:ifLoggedIn>
        <sec:ifNotLoggedIn>
            <p>You can't follow this user because you should
            <g:link controller="login">
                Sing In
            </g:link>
            </p>
        </sec:ifNotLoggedIn>

        <table>
            <thead>
            <tr>
                <th>Message</th>
                <th>Published</th>
            </tr>
            </thead>
            <tbody>
            <g:each in="${user.messages}">
                <tr>
                    <td>${it.text}</td>
                    <td width="15%">
                        <g:formatDate style="SHORT" type="datetime" date="${it.published.toDate()}"/>
                    </td>
                </tr>
            </g:each>
            </tbody>
        </table>
        <div><g:link controller="report" class="subscribe" action="forUser" id="${user.id}">Download messages</g:link></div>
    </g:else>
</div>
</body>
</html>

grails-app/views/user/singUp.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.singup.label"/></title>
</head>

<body>

<div id="create-user" class="content scaffold-create" role="main">
%{--    <h1><g:message code="default.singup.label"/></h1>--}%
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.user}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>

    <div id="singin">
        <div class="inner">
            <div class="fheader">Please <g:message code="default.singup.label"/></div>
            <g:form url="[action: 'save']" class="cssform">
                <p>
                    <label for="username">Username<span class="required-indicator">*</span>
                    </label>
                    <g:field type="text" class="text_" required="" name="username" id="username"/>
                </p>

                <p>
                    <label for="password">Password<span class="required-indicator">*</span>
                    </label>
                    <g:field class="text_" type="password" required="" name="password" id="password"/>
                </p>

                <p>
                    <g:submitButton name="submit"
                                    value="${message(code: 'default.button.singup.label', default: 'Sing Up')}"/>
                </p>
            </g:form>
        </div>
    </div>
</div>
</body>
</html>